this.getField("idioma1_escrito").setItems([
    "Nada",
    "Bajo",
    "Medio",
    "Alto",
    "Nativo",
  ]);
  this.getField("idioma1_hablado").setItems([
    "Nada",
    "Bajo",
    "Medio",
    "Alto",
    "Nativo",
  ]);
  
  this.getField("idioma2_escrito").setItems([
    "Nada",
    "Bajo",
    "Medio",
    "Alto",
    "Nativo",
  ]);
  this.getField("idioma2_hablado").setItems([
    "Nada",
    "Bajo",
    "Medio",
    "Alto",
    "Nativo",
  ]);
  
  this.getField("idioma3_escrito").setItems([
    "Nada",
    "Bajo",
    "Medio",
    "Alto",
    "Nativo",
  ]);
  this.getField("idioma3_hablado").setItems([
    "Nada",
    "Bajo",
    "Medio",
    "Alto",
    "Nativo",
  ]);
  
  this.getField("idioma4_escrito").setItems([
    "Nada",
    "Bajo",
    "Medio",
    "Alto",
    "Nativo",
  ]);
  this.getField("idioma4_hablado").setItems([
    "Nada",
    "Bajo",
    "Medio",
    "Alto",
    "Nativo",
  ]);
  
  this.getField("idioma5_escrito").setItems([
    "Nada",
    "Bajo",
    "Medio",
    "Alto",
    "Nativo",
  ]);
  this.getField("idioma5_hablado").setItems([
    "Nada",
    "Bajo",
    "Medio",
    "Alto",
    "Nativo",
  ]);