var index = 1;
while (index <= 8) {
  var ventajas = [
    "-",
    "Al límite",
    "Ambidiestría",
    "Armadura natural",
    "Buena suerte",
    "Reflejos rápidos",
    "Reflejos rápidos II",
    "Reflejos rápidos III",
    "Regeneración mejorada",
    "Regeneración mejorada II",
    "Regeneración mejorada III",
    "Resistencia física excepcional",
    "Resistencia física excepcional II",
    "Sueño ligero",
    "Tocado por el destino",
    "--- Solo durante la creación del personaje ---",
    "Afinidad animal",
    "Aprendizaje innato en llevar armadura",
    "Aprendizaje innato en llevar armadura II",
    "Aprendizaje innato en llevar armadura III",
    "Conecedor de todas las materias",
    "Dificil de matar",
    "Dificil de matar II",
    "Dificil de matar III",
    "Encanto",
    "Fondos iniciales",
    "Fondos iniciales II",
    "Fondos iniciales III",
    "Mente fria",
    "Inquietante",
    "Seductor",
    "Sentidos agudos",
    "Aprendizaje innato en VIGOR",
    "Aprendizaje innato en VIGOR II",
    "Aprendizaje innato en Frialdad",
    "Aprendizaje innato en Frialdad II",
    "Aprendizaje innato en Resdolor",
    "Aprendizaje innato en Resdolor II",
    "Aprendizaje innato en PERCEPTIVAS",
    "Aprendizaje innato en PERCEPTIVAS II",
    "Aprendizaje innato en Escuchar",
    "Aprendizaje innato en Escuchar II",
    "Aprendizaje innato en Ver",
    "Aprendizaje innato en Ver II",
    "Aprendizaje innato en Buscar",
    "Aprendizaje innato en Buscar II",
    "Aprendizaje innato en Rastrear",
    "Aprendizaje innato en Rastrear II",
    "Aprendizaje innato en SUBTERFUGIO",
    "Aprendizaje innato en SUBTERFUGIO II",
    "Aprendizaje innato en Cerrajeria",
    "Aprendizaje innato en Cerrajeria II",
    "Aprendizaje innato en Disfraz",
    "Aprendizaje innato en Disfraz II",
    "Aprendizaje innato en Ocultarse",
    "Aprendizaje innato en Ocultarse II",
    "Aprendizaje innato en Robo",
    "Aprendizaje innato en Robo II",
    "Aprendizaje innato en Sigilo",
    "Aprendizaje innato en Sigilo II",
    "Aprendizaje innato en Tramperia",
    "Aprendizaje innato en Tramperia II",
    "Aprendizaje innato en Venenos",
    "Aprendizaje innato en Venenos II",
    "Aprendizaje innato en INTELECTUALES",
    "Aprendizaje innato en INTELECTUALES II",
    "Aprendizaje innato en Animales",
    "Aprendizaje innato en Animales II",
    "Aprendizaje innato en Ciencia",
    "Aprendizaje innato en Ciencia II",
    "Aprendizaje innato en Herbolaria",
    "Aprendizaje innato en Herbolaria II",
    "Aprendizaje innato en Historia",
    "Aprendizaje innato en Historia II",
    "Aprendizaje innato en Ley",
    "Aprendizaje innato en Ley II",
    "Aprendizaje innato en Medicina",
    "Aprendizaje innato en Medicina II",
    "Aprendizaje innato en Memorizar",
    "Aprendizaje innato en Memorizar II",
    "Aprendizaje innato en Navegacion",
    "Aprendizaje innato en Navegacion II",
    "Aprendizaje innato en Ocultismo",
    "Aprendizaje innato en Ocultismo II",
    "Aprendizaje innato en Tasacion",
    "Aprendizaje innato en Tasacion II",
    "Aprendizaje innato en ATLETICAS",
    "Aprendizaje innato en ATLETICAS II",
    "Aprendizaje innato en Acrobacias",
    "Aprendizaje innato en Acrobacias II",
    "Aprendizaje innato en Atletismo",
    "Aprendizaje innato en Atletismo II",
    "Aprendizaje innato en Montar",
    "Aprendizaje innato en Montar II",
    "Aprendizaje innato en Nadar",
    "Aprendizaje innato en Nadar II",
    "Aprendizaje innato en Trepar",
    "Aprendizaje innato en Trepar II",
    "Aprendizaje innato en Saltar",
    "Aprendizaje innato en Saltar II",
    "Aprendizaje innato en SOCIALES",
    "Aprendizaje innato en SOCIALES II",
    "Aprendizaje innato en Comerciar",
    "Aprendizaje innato en Comerciar II",
    "Aprendizaje innato en Callejear",
    "Aprendizaje innato en Callejear II",
    "Aprendizaje innato en Estilo",
    "Aprendizaje innato en Estilo II",
    "Aprendizaje innato en Intimidar",
    "Aprendizaje innato en Intimidar II",
    "Aprendizaje innato en Etiqueta",
    "Aprendizaje innato en Etiqueta II",
    "Aprendizaje innato en Persuasion",
    "Aprendizaje innato en Persuasion II",
    "Aprendizaje innato en Adv. Social",
    "Aprendizaje innato en Adv. Social II",
    "Aprendizaje innato en CREATIVAS",
    "Aprendizaje innato en CREATIVAS II",
    "Aprendizaje innato en Arte",
    "Aprendizaje innato en Arte II",
    "Aprendizaje innato en Baile",
    "Aprendizaje innato en Baile II",
    "Aprendizaje innato en Forja",
    "Aprendizaje innato en Forja II",
    "Aprendizaje innato en Musica",
    "Aprendizaje innato en Musica II",
    "Aprendizaje innato en T. Manos",
    "Aprendizaje innato en T. Manos II",
    "Aprendizaje innato en Alquimia",
    "Aprendizaje innato en Alquimia II",
    "Aprendizaje innato en Sastreria",
    "Aprendizaje innato en Sastreria II",
    "Aprendizaje innato en Joyeria",
    "Aprendizaje innato en Joyeria II",
    "Aprendizaje innato en Caligrafia",
    "Aprendizaje innato en Caligrafia II",
    "Aprendizaje innato en Mates",
    "Aprendizaje innato en Mates II",
    "Aprendizaje innato en Cocina",
    "Aprendizaje innato en Cocina II",
    "Apto en VIGOR",
    "Apto en Frialdad",
    "Apto en Frialdad II",
    "Apto en Resdolor",
    "Apto en Resdolor II",
    "Apto en PERCEPTIVAS",
    "Apto en Escuchar",
    "Apto en Escuchar II",
    "Apto en Ver",
    "Apto en Ver II",
    "Apto en Buscar",
    "Apto en Buscar II",
    "Apto en Rastrear",
    "Apto en Rastrear II",
    "Apto en SUBTERFUGIO",
    "Apto en Cerrajeria",
    "Apto en Cerrajeria II",
    "Apto en Disfraz",
    "Apto en Disfraz II",
    "Apto en Ocultarse",
    "Apto en Ocultarse II",
    "Apto en Robo",
    "Apto en Robo II",
    "Apto en Sigilo",
    "Apto en Sigilo II",
    "Apto en Tramperia",
    "Apto en Tramperia II",
    "Apto en Venenos",
    "Apto en Venenos II",
    "Apto en INTELECTUALES",
    "Apto en Animales",
    "Apto en Animales II",
    "Apto en Ciencia",
    "Apto en Ciencia II",
    "Apto en Herbolaria",
    "Apto en Herbolaria II",
    "Apto en Historia",
    "Apto en Historia II",
    "Apto en Ley",
    "Apto en Ley II",
    "Apto en Medicina",
    "Apto en Medicina II",
    "Apto en Memorizar",
    "Apto en Memorizar II",
    "Apto en Navegacion",
    "Apto en Navegacion II",
    "Apto en Ocultismo",
    "Apto en Ocultismo II",
    "Apto en Tasacion",
    "Apto en Tasacion II",
    "Apto en ATLETICAS",
    "Apto en Acrobacias",
    "Apto en Acrobacias II",
    "Apto en Atletismo",
    "Apto en Atletismo II",
    "Apto en Montar",
    "Apto en Montar II",
    "Apto en Nadar",
    "Apto en Nadar II",
    "Apto en Trepar",
    "Apto en Trepar II",
    "Apto en Saltar",
    "Apto en Saltar II",
    "Apto en SOCIALES",
    "Apto en Comerciar",
    "Apto en Comerciar II",
    "Apto en Callejear",
    "Apto en Callejear II",
    "Apto en Estilo",
    "Apto en Estilo II",
    "Apto en Intimidar",
    "Apto en Intimidar II",
    "Apto en Etiqueta",
    "Apto en Etiqueta II",
    "Apto en Persuasion",
    "Apto en Persuasion II",
    "Apto en Adv. Social",
    "Apto en Adv. Social II",
    "Apto en CREATIVAS",
    "Apto en Arte",
    "Apto en Arte II",
    "Apto en Baile",
    "Apto en Baile II",
    "Apto en Forja",
    "Apto en Forja II",
    "Apto en Musica",
    "Apto en Musica II",
    "Apto en T. Manos",
    "Apto en T. Manos II",
    "Apto en Alquimia",
    "Apto en Alquimia II",
    "Apto en Sastreria",
    "Apto en Sastreria II",
    "Apto en Joyeria",
    "Apto en Joyeria II",
    "Apto en Caligrafia",
    "Apto en Caligrafia II",
    "Apto en Mates",
    "Apto en Mates II",
    "Apto en Cocina",
    "Apto en Cocina II"
  ];
  this.getField("ventaja" + index).setItems(ventajas);
  index++;
}